export enum ROUTES {
  home = '/',
  inbox = '/inbox',
  receiptDetails = 'receipt-details',
  filesUploadPreview = 'files-upload-preview',
  login = '/login',
  sign_up = '/sign-up',
  master = '/master',
  termsOfService = '/settings/terms-of-service',
  privacyPolicy = '/settings/privacy-policy',
  settings = '/settings/my-account',
  support = '/support',
  preference = '/preference',
  forgotPassword = '/forgot-password',
  resetPassword = '/reset-password/:token',
  capiumLogin = '/capium-login',
  notFound = '*',
}
