export const COMPANY_LIST_INITIAL_STATE = {
  companyName: '',
  searchValue: '',
  isLoading: false,
  isContentLoading: false,
  logoSrc: '',
  logoName: '',
  isSearching: false,
  isFocus: false,
  selectedItemId: '',
  searchedCompanies: [],
  isFetchingData: true,
  companyLogo: null,
  selectedCompany: null,
  isCompanyLogoLoading: false,
  prevCompanyName: '',
  prevLogoSrc: '',
  isDeleteCompanyLogo: false,
};
